"""Output helpers for LangGraph scripts.

Every script in this runner writes its final result through
:func:`write_output`. That gives us a single convention for:

  - **Where files land**: `outputs/` next to the script (created if missing).
  - **How they're named**: `<script-stem>_<YYYYMMDD-HHMMSS>.<ext>` — the stem
    on the front directly ties an output back to its source script.
  - **What metadata they carry**: a YAML-style frontmatter block (for
    Markdown outputs) recording the source script, when it ran, and the
    runner that produced it. The UI parses this and shows a small
    "generated by …" badge above the rendered document.

Usage in a script::

    from script_io import write_output
    output_path = write_output(my_markdown_text, __file__, prompt=user_prompt)

That's all the script needs. Returns the absolute :class:`pathlib.Path`
of the file that was written.
"""
from __future__ import annotations

import datetime
import re
from pathlib import Path
from typing import Optional, Tuple


# Folder name (relative to the runner's install root) where outputs land.
# Kept as a constant rather than configurable: the matching /api/outputs
# endpoint and the index.html UI both assume this same name.
OUTPUTS_DIRNAME = "outputs"

# Identifies what produced the file. Pinned here so the UI can rely on it.
RUNNER_TAG = "langchain_runner"


def _install_root() -> Path:
    """Return the runner's install root.

    `script_io.py` is copied into the install location (see setup.py's
    RUNTIME_FILES). Scripts that import this module thus get the right
    root regardless of where they're invoked from.
    """
    return Path(__file__).resolve().parent


def _outputs_dir() -> Path:
    """Resolve (and create if missing) the outputs directory."""
    d = _install_root() / OUTPUTS_DIRNAME
    d.mkdir(parents=True, exist_ok=True)
    return d


def _stem_from_script(script_file: str) -> str:
    """Strip path + extension, leaving just the script's filename stem."""
    return Path(script_file).stem


def _timestamp() -> str:
    """Compact, file-safe timestamp: YYYYMMDD-HHMMSS."""
    return datetime.datetime.now().strftime("%Y%m%d-%H%M%S")


def _build_frontmatter(
    script_file: str,
    prompt: Optional[str] = None,
    extras: Optional[dict] = None,
) -> str:
    """Build a YAML-style frontmatter block. Plain string assembly is
    enough — we control the inputs and don't need a full YAML library
    dependency just for this.
    """
    lines = ["---"]
    lines.append(f"source: {Path(script_file).name}")
    lines.append(f"generated_at: {datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds')}")
    lines.append(f"runner: {RUNNER_TAG}")
    if prompt:
        # Quote the prompt to keep multi-line values from breaking parsers.
        safe = prompt.replace('"', '\\"').replace("\n", " ").strip()
        if len(safe) > 200:
            safe = safe[:197] + "..."
        lines.append(f'prompt: "{safe}"')
    if extras:
        for k, v in extras.items():
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines) + "\n\n"


# Patterns that strongly indicate the content is HTML. Looked up
# case-insensitively, anywhere in the first 2000 chars — so generated
# scripts that prepend a markdown wrapper around HTML output (e.g.
# "# Result\n\n**Date:**…\n\n---\n\n<!DOCTYPE html>…") still get
# classified correctly. The detector trims the wrapper before writing.
_HTML_SIGNATURE = re.compile(
    r"<!DOCTYPE\s+html\b"
    r"|<html[\s>]"
    r"|<head[\s>]"
    r"|<body[\s>]",
    re.IGNORECASE,
)


def _detect_format_and_strip(content: str) -> Tuple[str, str]:
    """Return ``(ext, body)``.

    If HTML signatures are found anywhere in the first 2000 chars,
    ``ext`` is ``"html"`` and ``body`` is the content from the first
    HTML signature onward (any markdown wrapper prefix is dropped, so
    browsers don't see stray ``#``/``---``/``**Prompt:**`` lines above
    the real document).

    Otherwise ``ext`` is ``"md"`` and ``body`` is the full content.
    """
    window = content[:2000]
    m = _HTML_SIGNATURE.search(window)
    if m:
        return ("html", content[m.start():])
    return ("md", content)


def write_output(
    content: str,
    script_file: str,
    *,
    ext: Optional[str] = None,
    prompt: Optional[str] = None,
    extras: Optional[dict] = None,
) -> Path:
    """Write `content` into `outputs/<stem>_<ts>.<ext>` and return its path.

    When ``ext`` is ``None`` (the default), the extension is inferred
    from the content: HTML signatures → ``"html"``, everything else →
    ``"md"``. Callers can force a specific extension by passing it.

    For Markdown outputs, a YAML frontmatter block is prepended so the
    UI can show origin metadata. For other extensions the content is
    written verbatim — HTML / JSON / plaintext shouldn't be polluted
    with YAML at the top (browsers would render it as garbage).

    Args:
        content: The body of the file (e.g., the final assistant text).
        script_file: Pass ``__file__`` from the caller. Used to derive
            the filename stem.
        ext: File extension without the leading dot. Default is
            auto-detect — see :func:`_detect_ext`.
        prompt: Optional original user prompt; recorded in frontmatter
            for Markdown outputs only.
        extras: Optional dict of extra `key: value` frontmatter entries
            (Markdown outputs only). String values only.

    Returns:
        Absolute path of the file that was written.
    """
    if ext is None:
        # Auto-detect AND strip the markdown wrapper if the content is
        # actually HTML. This is the generic path that works regardless
        # of how the script (or the upstream code generator) framed the
        # output before calling us.
        ext, content = _detect_format_and_strip(content)
    stem = _stem_from_script(script_file)
    ts = _timestamp()
    out_path = _outputs_dir() / f"{stem}_{ts}.{ext}"
    if ext == "md":
        body = _build_frontmatter(script_file, prompt=prompt, extras=extras) + content
    else:
        # HTML / JSON / plaintext: write verbatim. Frontmatter would
        # break HTML and looks like garbage in JSON/text.
        body = content
    out_path.write_text(body, encoding="utf-8")
    return out_path
