"""Unit tests for ScheduledWorkflowService (Phase 8, Task 1).

Port of backend/src/AgentTeam/Services/ScheduledWorkflowService.php (341
lines). A FakeDb records every statement so SQL can be asserted
whitespace-normalized against the PHP source, and params asserted exactly.

The `calculateNextRun` fixture table below was generated by running the
PHP algorithm verbatim through the live interpreter:

    /Applications/XAMPP/xamppfiles/bin/php -f gen_fixture.php

against a script that copies ScheduledWorkflowService::calculateNextRun's
body exactly (PHP's default timezone is Europe/Berlin, matching
PHP_TIMEZONE's default in app/config.py). See task-1-report.md for the
full generator script and raw output.
"""
from __future__ import annotations

import re

from app.agent_team.services.scheduled_workflow_service import ScheduledWorkflowService


def norm(sql: str) -> str:
    return re.sub(r'\s+', ' ', sql).strip()


class FakeDb:
    """Records every statement so tests can assert SQL (whitespace-normalized)
    and params. Queued return values are consumed in call order per method."""

    def __init__(self, one=None, all_=None, insert_id=1, rowcount=1):
        self.one_queue = list(one) if one else []
        self.all_queue = list(all_) if all_ else []
        self.insert_id = insert_id
        self.rowcount = rowcount
        self.calls = []

    def fetch_one(self, sql, params=None):
        self.calls.append(('fetch_one', sql, params))
        return self.one_queue.pop(0) if self.one_queue else None

    def fetch_all(self, sql, params=None):
        self.calls.append(('fetch_all', sql, params))
        return self.all_queue.pop(0) if self.all_queue else []

    def execute(self, sql, params=None):
        self.calls.append(('execute', sql, params))
        return self.rowcount

    def insert(self, sql, params=None):
        self.calls.append(('insert', sql, params))
        return self.insert_id


SCHEDULE_ROW = {
    'id': 7, 'user_id': 1, 'workflow_id': 3, 'input_prompt': 'go',
    'scheduled_time': '2026-01-15 10:00:00', 'status': 'pending',
    'repeat_type': 'daily', 'repeat_interval': 1, 'last_run': None,
    'next_run': '2026-01-15 10:00:00', 'created_at': '2026-01-01 00:00:00',
    'error_message': None, 'workflow_name': 'My Workflow',
}


# ---------------------------------------------------------------------------
# create
# ---------------------------------------------------------------------------

def test_create_inserts_and_returns_found_row():
    db = FakeDb(one=[SCHEDULE_ROW], insert_id=7)
    svc = ScheduledWorkflowService(db)
    result = svc.create({
        'user_id': 1, 'workflow_id': 3, 'input_prompt': 'go',
        'scheduled_time': '2026-01-15 10:00:00', 'repeat_type': 'daily', 'repeat_interval': 1,
    })
    assert result == SCHEDULE_ROW

    insert_call = db.calls[0]
    assert insert_call[0] == 'insert'
    assert norm(insert_call[1]) == norm(
        "INSERT INTO scheduled_workflows"
        " (user_id, workflow_id, input_prompt, scheduled_time, status, repeat_type, repeat_interval, next_run, created_at)"
        " VALUES"
        " (:user_id, :workflow_id, :input_prompt, :scheduled_time, 'pending', :repeat_type, :repeat_interval, :next_run, NOW())"
    )
    assert insert_call[2] == {
        'user_id': 1, 'workflow_id': 3, 'input_prompt': 'go',
        'scheduled_time': '2026-01-15 10:00:00', 'repeat_type': 'daily',
        'repeat_interval': 1, 'next_run': '2026-01-15 10:00:00',
    }

    find_call = db.calls[1]
    assert find_call == ('fetch_one', find_call[1], {'id': 7})


def test_create_defaults_repeat_type_and_interval_and_null_prompt():
    db = FakeDb(one=[SCHEDULE_ROW], insert_id=9)
    svc = ScheduledWorkflowService(db)
    svc.create({'user_id': 1, 'workflow_id': 3, 'scheduled_time': '2026-02-01 08:00:00'})
    params = db.calls[0][2]
    assert params['input_prompt'] is None
    assert params['repeat_type'] == 'none'
    assert params['repeat_interval'] == 1


# ---------------------------------------------------------------------------
# update
# ---------------------------------------------------------------------------

def test_update_not_found_returns_none():
    db = FakeDb(one=[None])
    svc = ScheduledWorkflowService(db)
    assert svc.update(7, 1, {'status': 'paused'}) is None


def test_update_wrong_owner_returns_none():
    db = FakeDb(one=[SCHEDULE_ROW])
    svc = ScheduledWorkflowService(db)
    assert svc.update(7, 999, {'status': 'paused'}) is None


def test_update_no_fields_returns_schedule_unchanged():
    db = FakeDb(one=[SCHEDULE_ROW])
    svc = ScheduledWorkflowService(db)
    result = svc.update(7, 1, {})
    assert result == SCHEDULE_ROW
    assert len(db.calls) == 1  # only the ownership-check findById, no UPDATE


def test_update_all_fields():
    db = FakeDb(one=[SCHEDULE_ROW, SCHEDULE_ROW])
    svc = ScheduledWorkflowService(db)
    svc.update(7, 1, {
        'scheduled_time': '2026-03-01 09:00:00', 'input_prompt': 'new prompt',
        'repeat_type': 'weekly', 'repeat_interval': 2, 'status': 'paused',
    })
    update_call = db.calls[1]
    assert update_call[0] == 'execute'
    assert norm(update_call[1]) == norm(
        "UPDATE scheduled_workflows SET"
        " scheduled_time = :scheduled_time, next_run = :next_run,"
        " input_prompt = :input_prompt,"
        " repeat_type = :repeat_type,"
        " repeat_interval = :repeat_interval,"
        " status = :status"
        " WHERE id = :id"
    )
    assert update_call[2] == {
        'id': 7, 'scheduled_time': '2026-03-01 09:00:00', 'next_run': '2026-03-01 09:00:00',
        'input_prompt': 'new prompt', 'repeat_type': 'weekly', 'repeat_interval': 2, 'status': 'paused',
    }


def test_update_partial_field_only_status():
    db = FakeDb(one=[SCHEDULE_ROW, SCHEDULE_ROW])
    svc = ScheduledWorkflowService(db)
    svc.update(7, 1, {'status': 'paused'})
    update_call = db.calls[1]
    assert norm(update_call[1]) == norm("UPDATE scheduled_workflows SET status = :status WHERE id = :id")
    assert update_call[2] == {'id': 7, 'status': 'paused'}


# ---------------------------------------------------------------------------
# delete
# ---------------------------------------------------------------------------

def test_delete_true_on_rowcount():
    db = FakeDb(rowcount=1)
    svc = ScheduledWorkflowService(db)
    assert svc.delete(7, 1) is True
    call = db.calls[0]
    assert norm(call[1]) == norm("DELETE FROM scheduled_workflows WHERE id = :id AND user_id = :user_id")
    assert call[2] == {'id': 7, 'user_id': 1}


def test_delete_false_on_no_rows():
    db = FakeDb(rowcount=0)
    svc = ScheduledWorkflowService(db)
    assert svc.delete(7, 1) is False


# ---------------------------------------------------------------------------
# findById / findByUser / findByWorkflow
# ---------------------------------------------------------------------------

def test_find_by_id_found():
    db = FakeDb(one=[SCHEDULE_ROW])
    svc = ScheduledWorkflowService(db)
    assert svc.findById(7) == SCHEDULE_ROW
    call = db.calls[0]
    assert norm(call[1]) == norm(
        "SELECT sw.*, w.name as workflow_name"
        " FROM scheduled_workflows sw"
        " LEFT JOIN agent_workflows w ON sw.workflow_id = w.id"
        " WHERE sw.id = :id"
    )
    assert call[2] == {'id': 7}


def test_find_by_id_not_found():
    db = FakeDb(one=[None])
    svc = ScheduledWorkflowService(db)
    assert svc.findById(999) is None


def test_find_by_user():
    db = FakeDb(all_=[[SCHEDULE_ROW]])
    svc = ScheduledWorkflowService(db)
    result = svc.findByUser(1)
    assert result == [SCHEDULE_ROW]
    call = db.calls[0]
    assert norm(call[1]) == norm(
        "SELECT sw.*, w.name as workflow_name"
        " FROM scheduled_workflows sw"
        " LEFT JOIN agent_workflows w ON sw.workflow_id = w.id"
        " WHERE sw.user_id = :user_id"
        " ORDER BY sw.next_run ASC"
    )
    assert call[2] == {'user_id': 1}


def test_find_by_workflow():
    db = FakeDb(all_=[[SCHEDULE_ROW]])
    svc = ScheduledWorkflowService(db)
    result = svc.findByWorkflow(3, 1)
    assert result == [SCHEDULE_ROW]
    call = db.calls[0]
    assert norm(call[1]) == norm(
        "SELECT sw.*, w.name as workflow_name"
        " FROM scheduled_workflows sw"
        " LEFT JOIN agent_workflows w ON sw.workflow_id = w.id"
        " WHERE sw.workflow_id = :workflow_id AND sw.user_id = :user_id"
        " ORDER BY sw.next_run ASC"
    )
    assert call[2] == {'workflow_id': 3, 'user_id': 1}


# ---------------------------------------------------------------------------
# getDueSchedules
# ---------------------------------------------------------------------------

def test_get_due_schedules_predicate_and_no_params():
    db = FakeDb(all_=[[SCHEDULE_ROW]])
    svc = ScheduledWorkflowService(db)
    result = svc.getDueSchedules()
    assert result == [SCHEDULE_ROW]
    call = db.calls[0]
    assert call[0] == 'fetch_all'
    assert norm(call[1]) == norm(
        "SELECT sw.*, w.name as workflow_name, u.email as user_email"
        " FROM scheduled_workflows sw"
        " LEFT JOIN agent_workflows w ON sw.workflow_id = w.id"
        " LEFT JOIN users u ON sw.user_id = u.id"
        " WHERE sw.status = 'pending'"
        " AND sw.next_run <= NOW()"
        " ORDER BY sw.next_run ASC"
        " LIMIT 50"
    )
    assert call[2] is None


# ---------------------------------------------------------------------------
# markRunning / markCompleted / markFailed
# ---------------------------------------------------------------------------

def test_mark_running():
    db = FakeDb()
    svc = ScheduledWorkflowService(db)
    svc.markRunning(7)
    call = db.calls[0]
    assert norm(call[1]) == norm("UPDATE scheduled_workflows SET status = 'running' WHERE id = :id")
    assert call[2] == {'id': 7}


def test_mark_completed_missing_schedule_is_noop():
    db = FakeDb(one=[None])
    svc = ScheduledWorkflowService(db)
    svc.markCompleted(999)
    assert len(db.calls) == 1  # only the findById lookup


def test_mark_completed_one_time_marks_completed():
    row = {**SCHEDULE_ROW, 'repeat_type': 'none'}
    db = FakeDb(one=[row])
    svc = ScheduledWorkflowService(db)
    svc.markCompleted(7, 'exec-1')
    call = db.calls[1]
    assert norm(call[1]) == norm(
        "UPDATE scheduled_workflows SET status = 'completed', last_run = NOW() WHERE id = :id"
    )
    assert call[2] == {'id': 7}


def test_mark_completed_recurring_calculates_next_run():
    row = {**SCHEDULE_ROW, 'repeat_type': 'daily', 'repeat_interval': 2, 'next_run': '2026-01-15 10:00:00'}
    db = FakeDb(one=[row])
    svc = ScheduledWorkflowService(db)
    svc.markCompleted(7)
    call = db.calls[1]
    assert norm(call[1]) == norm(
        "UPDATE scheduled_workflows SET status = 'pending', last_run = NOW(), next_run = :next_run WHERE id = :id"
    )
    assert call[2] == {'id': 7, 'next_run': '2026-01-17 10:00:00'}


def test_mark_failed_missing_schedule_is_noop():
    db = FakeDb(one=[None])
    svc = ScheduledWorkflowService(db)
    svc.markFailed(999, 'boom')
    assert len(db.calls) == 1


def test_mark_failed_one_time_marks_failed():
    row = {**SCHEDULE_ROW, 'repeat_type': 'none'}
    db = FakeDb(one=[row])
    svc = ScheduledWorkflowService(db)
    svc.markFailed(7, 'boom')
    call = db.calls[1]
    assert norm(call[1]) == norm(
        "UPDATE scheduled_workflows"
        " SET status = 'failed', error_message = :error, last_run = NOW()"
        " WHERE id = :id"
    )
    assert call[2] == {'id': 7, 'error': 'boom'}


def test_mark_failed_recurring_resets_to_pending_with_next_run():
    row = {**SCHEDULE_ROW, 'repeat_type': 'hourly', 'repeat_interval': 1, 'next_run': '2026-01-15 10:00:00'}
    db = FakeDb(one=[row])
    svc = ScheduledWorkflowService(db)
    svc.markFailed(7, 'boom')
    call = db.calls[1]
    assert norm(call[1]) == norm(
        "UPDATE scheduled_workflows"
        " SET status = 'pending', error_message = :error, last_run = NOW(), next_run = :next_run"
        " WHERE id = :id"
    )
    assert call[2] == {'id': 7, 'error': 'boom', 'next_run': '2026-01-15 11:00:00'}


# ---------------------------------------------------------------------------
# pause / resume
# ---------------------------------------------------------------------------

def test_pause_true_on_rowcount():
    db = FakeDb(rowcount=1)
    svc = ScheduledWorkflowService(db)
    assert svc.pause(7, 1) is True
    call = db.calls[0]
    assert norm(call[1]) == norm(
        "UPDATE scheduled_workflows SET status = 'paused' WHERE id = :id AND user_id = :user_id"
    )
    assert call[2] == {'id': 7, 'user_id': 1}


def test_pause_false_on_no_rows():
    db = FakeDb(rowcount=0)
    svc = ScheduledWorkflowService(db)
    assert svc.pause(7, 1) is False


def test_resume_true_on_rowcount():
    db = FakeDb(rowcount=1)
    svc = ScheduledWorkflowService(db)
    assert svc.resume(7, 1) is True
    call = db.calls[0]
    assert norm(call[1]) == norm(
        "UPDATE scheduled_workflows"
        " SET status = 'pending'"
        " WHERE id = :id AND user_id = :user_id AND status = 'paused'"
    )
    assert call[2] == {'id': 7, 'user_id': 1}


def test_resume_false_on_no_rows():
    db = FakeDb(rowcount=0)
    svc = ScheduledWorkflowService(db)
    assert svc.resume(7, 1) is False


# ---------------------------------------------------------------------------
# getStats
# ---------------------------------------------------------------------------

def test_get_stats_shape():
    stats_row = {'total': 6, 'pending': '3', 'running': '1', 'completed': '1', 'failed': '1', 'paused': '0'}
    db = FakeDb(one=[stats_row])
    svc = ScheduledWorkflowService(db)
    result = svc.getStats(1)
    assert result == stats_row
    call = db.calls[0]
    assert norm(call[1]) == norm(
        "SELECT"
        " COUNT(*) as total,"
        " SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending,"
        " SUM(CASE WHEN status = 'running' THEN 1 ELSE 0 END) as running,"
        " SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as completed,"
        " SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) as failed,"
        " SUM(CASE WHEN status = 'paused' THEN 1 ELSE 0 END) as paused"
        " FROM scheduled_workflows"
        " WHERE user_id = :user_id"
    )
    assert call[2] == {'user_id': 1}


# ---------------------------------------------------------------------------
# calculateNextRun fixture table
#
# Generated via:
#   /Applications/XAMPP/xamppfiles/bin/php -f gen_fixture.php
# running ScheduledWorkflowService::calculateNextRun's exact algorithm
# against PHP's default timezone (Europe/Berlin == PHP_TIMEZONE default).
# Covers hourly/daily/weekly/monthly, interval 1/2/3, month-end overflow
# (incl. across a leap year and off a leap day), a DST spring-forward gap
# hit directly through each of hourly/daily/monthly addition, and a DST
# fall-back ambiguous hour.
# ---------------------------------------------------------------------------

NEXT_RUN_FIXTURES = [
    ('2026-01-15 10:00:00', 'hourly', 1, '2026-01-15 11:00:00'),
    ('2026-01-15 10:00:00', 'hourly', 2, '2026-01-15 12:00:00'),
    ('2026-01-15 23:00:00', 'hourly', 3, '2026-01-16 02:00:00'),
    ('2026-01-15 10:00:00', 'daily', 1, '2026-01-16 10:00:00'),
    ('2026-01-15 10:00:00', 'daily', 2, '2026-01-17 10:00:00'),
    ('2026-01-30 10:00:00', 'daily', 3, '2026-02-02 10:00:00'),
    ('2026-01-15 10:00:00', 'weekly', 1, '2026-01-22 10:00:00'),
    ('2026-01-15 10:00:00', 'weekly', 2, '2026-01-29 10:00:00'),
    ('2026-01-15 10:00:00', 'weekly', 3, '2026-02-05 10:00:00'),
    ('2026-01-31 10:00:00', 'monthly', 1, '2026-03-03 10:00:00'),   # Jan31+1M overflow (Feb non-leap)
    ('2026-01-31 10:00:00', 'monthly', 2, '2026-03-31 10:00:00'),   # Jan31+2M lands on 31-day month
    ('2026-01-31 10:00:00', 'monthly', 3, '2026-05-01 10:00:00'),   # Jan31+3M overflow (Apr has 30 days)
    ('2026-08-31 10:00:00', 'monthly', 1, '2026-10-01 10:00:00'),   # Aug31+1M overflow (Sep has 30 days)
    ('2024-01-31 10:00:00', 'monthly', 1, '2024-03-02 10:00:00'),   # leap year: Feb 2024 has 29 days
    ('2024-02-29 10:00:00', 'monthly', 1, '2024-03-29 10:00:00'),   # leap day + 1M, no overflow
    ('2024-02-29 10:00:00', 'monthly', 12, '2025-03-01 10:00:00'),  # leap day + 12M overflow (Feb 2025 has 28 days)
    ('2026-03-29 01:30:00', 'hourly', 1, '2026-03-29 03:30:00'),    # DST spring-forward gap via hourly add
    ('2026-03-28 02:30:00', 'daily', 1, '2026-03-29 03:30:00'),     # DST spring-forward gap via daily add
    ('2026-01-29 02:30:00', 'monthly', 2, '2026-03-29 03:30:00'),   # DST spring-forward gap via monthly add
    ('2026-10-24 20:00:00', 'hourly', 6, '2026-10-25 02:00:00'),    # DST fall-back ambiguous hour
]


def test_calculate_next_run_fixture_table():
    db = FakeDb()
    svc = ScheduledWorkflowService(db)
    assert len(NEXT_RUN_FIXTURES) == 20
    for current_run, repeat_type, interval, expected in NEXT_RUN_FIXTURES:
        got = svc._calculateNextRun(current_run, repeat_type, interval)
        assert got == expected, f'{current_run} {repeat_type} {interval}: got {got}, expected {expected}'
